name: Main

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-20.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
        dotnet tool restore
        dotnet paket restore
        dotnet build
    - name: Test
      run: |
        dotnet test
