name: Main

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
      run: |
        dotnet tool restore
        dotnet paket restore
        dotnet build
        dotnet test
