name: Main

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
        echo "{DOTNET_CLI_TELEMETRY_OPTOUT}={true}" >> $GITHUB_ENV
        echo "{DOTNET_NOLOGO}={true}" >> $GITHUB_ENV
        dotnet tool restore
        dotnet paket restore
        dotnet build
        dotnet test
